"""Word-level RTL recovery pipeline."""

from .models import (
    ExpressionCandidate,
    MethodRecommendation,
    OutputCluster,
    PlanRevision,
    PlanStep,
    RecoveredWord,
    RecoveryFeedback,
    RecoveryPlan,
    RecoveryReport,
    SupportCut,
    ToolProfile,
    VerificationResult,
    WordAnalysis,
)
from .ir import (
    CandidateIR,
    CexIR,
    CircuitFingerprint,
    EvidenceItem,
    HypothesisIR,
    LearningEvent,
    LocalRecoveryKB,
    ReasoningGraphNode,
    RecoveryIRRecorder,
    RecoveryRunIR,
    ToolCallIR,
    recovery_feature_tokens,
)
from .plan import plan_recovery
from .pipeline import recover_expression_data, recover_rtl_data
from .report import format_recovery_plan, format_recovery_report, format_word_analysis
from .small_tools import (
    check_polynomial_lowbits_data,
    fit_template_data,
    influence_profile_data,
    infer_native_expr_data,
    infer_pysr_expr_data,
    probe_target_data,
    split_control_cases_data,
    validate_expr_data,
)
from .tool_profiles import TOOL_PROFILES, get_tool_profile
from .word import analyze_words

__all__ = [
    "ExpressionCandidate",
    "MethodRecommendation",
    "OutputCluster",
    "PlanRevision",
    "PlanStep",
    "RecoveredWord",
    "RecoveryFeedback",
    "RecoveryPlan",
    "RecoveryReport",
    "SupportCut",
    "ToolProfile",
    "VerificationResult",
    "WordAnalysis",
    "CandidateIR",
    "CexIR",
    "CircuitFingerprint",
    "EvidenceItem",
    "HypothesisIR",
    "LearningEvent",
    "LocalRecoveryKB",
    "ReasoningGraphNode",
    "RecoveryIRRecorder",
    "RecoveryRunIR",
    "ToolCallIR",
    "TOOL_PROFILES",
    "analyze_words",
    "format_recovery_plan",
    "format_recovery_report",
    "format_word_analysis",
    "check_polynomial_lowbits_data",
    "fit_template_data",
    "influence_profile_data",
    "infer_native_expr_data",
    "infer_pysr_expr_data",
    "plan_recovery",
    "probe_target_data",
    "recover_expression_data",
    "recover_rtl_data",
    "split_control_cases_data",
    "validate_expr_data",
    "get_tool_profile",
    "recovery_feature_tokens",
]
